// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/event.proto

package tracker.datatypes;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>IMPRESSION = 1;</code>
     */
    IMPRESSION(1),
    /**
     * <code>CLICK = 2;</code>
     */
    CLICK(2),
    /**
     * <code>CONVERSION = 3;</code>
     */
    CONVERSION(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>IMPRESSION = 1;</code>
     */
    public static final int IMPRESSION_VALUE = 1;
    /**
     * <code>CLICK = 2;</code>
     */
    public static final int CLICK_VALUE = 2;
    /**
     * <code>CONVERSION = 3;</code>
     */
    public static final int CONVERSION_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return IMPRESSION;
        case 2: return CLICK;
        case 3: return CONVERSION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return tracker.datatypes.Events.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EventType)
  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique event ID. UUID (128 bit), big endian.
     * </pre>
     *
     * <code>bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <pre>
     * Timestamp of the event. UTC timestamp millis.
     * </pre>
     *
     * <code>uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     * Type of event.
     * </pre>
     *
     * <code>.EventType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * Type of event.
     * </pre>
     *
     * <code>.EventType type = 3;</code>
     */
    tracker.datatypes.Events.EventType getType();

    /**
     * <pre>
     * Unique device (~ user) identifier. UUID (128 bit), big endian.
     * Typically stored in a cookie in the browser.
     * </pre>
     *
     * <code>bytes device_id = 4;</code>
     */
    com.google.protobuf.ByteString getDeviceId();
  }
  /**
   * <pre>
   * Input Data
   * </pre>
   *
   * Protobuf type {@code Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Event)
      EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      type_ = 0;
      deviceId_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              id_ = input.readBytes();
              break;
            }
            case 16: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 34: {

              deviceId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tracker.datatypes.Events.internal_static_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tracker.datatypes.Events.internal_static_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tracker.datatypes.Events.Event.class, tracker.datatypes.Events.Event.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <pre>
     * Unique event ID. UUID (128 bit), big endian.
     * </pre>
     *
     * <code>bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <pre>
     * Timestamp of the event. UTC timestamp millis.
     * </pre>
     *
     * <code>uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     * Type of event.
     * </pre>
     *
     * <code>.EventType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Type of event.
     * </pre>
     *
     * <code>.EventType type = 3;</code>
     */
    public tracker.datatypes.Events.EventType getType() {
      tracker.datatypes.Events.EventType result = tracker.datatypes.Events.EventType.valueOf(type_);
      return result == null ? tracker.datatypes.Events.EventType.UNRECOGNIZED : result;
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString deviceId_;
    /**
     * <pre>
     * Unique device (~ user) identifier. UUID (128 bit), big endian.
     * Typically stored in a cookie in the browser.
     * </pre>
     *
     * <code>bytes device_id = 4;</code>
     */
    public com.google.protobuf.ByteString getDeviceId() {
      return deviceId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(2, timestamp_);
      }
      if (type_ != tracker.datatypes.Events.EventType.UNKNOWN.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (!deviceId_.isEmpty()) {
        output.writeBytes(4, deviceId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (type_ != tracker.datatypes.Events.EventType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (!deviceId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, deviceId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tracker.datatypes.Events.Event)) {
        return super.equals(obj);
      }
      tracker.datatypes.Events.Event other = (tracker.datatypes.Events.Event) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && type_ == other.type_;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tracker.datatypes.Events.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracker.datatypes.Events.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracker.datatypes.Events.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracker.datatypes.Events.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracker.datatypes.Events.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracker.datatypes.Events.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracker.datatypes.Events.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tracker.datatypes.Events.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tracker.datatypes.Events.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tracker.datatypes.Events.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tracker.datatypes.Events.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tracker.datatypes.Events.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tracker.datatypes.Events.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Input Data
     * </pre>
     *
     * Protobuf type {@code Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Event)
        tracker.datatypes.Events.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tracker.datatypes.Events.internal_static_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tracker.datatypes.Events.internal_static_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tracker.datatypes.Events.Event.class, tracker.datatypes.Events.Event.Builder.class);
      }

      // Construct using tracker.Events.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;

        timestamp_ = 0L;

        type_ = 0;

        deviceId_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tracker.datatypes.Events.internal_static_Event_descriptor;
      }

      public tracker.datatypes.Events.Event getDefaultInstanceForType() {
        return tracker.datatypes.Events.Event.getDefaultInstance();
      }

      public tracker.datatypes.Events.Event build() {
        tracker.datatypes.Events.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tracker.datatypes.Events.Event buildPartial() {
        tracker.datatypes.Events.Event result = new tracker.datatypes.Events.Event(this);
        result.id_ = id_;
        result.timestamp_ = timestamp_;
        result.type_ = type_;
        result.deviceId_ = deviceId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tracker.datatypes.Events.Event) {
          return mergeFrom((tracker.datatypes.Events.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tracker.datatypes.Events.Event other) {
        if (other == tracker.datatypes.Events.Event.getDefaultInstance()) return this;
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getDeviceId() != com.google.protobuf.ByteString.EMPTY) {
          setDeviceId(other.getDeviceId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tracker.datatypes.Events.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tracker.datatypes.Events.Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Unique event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <pre>
       * Unique event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * Timestamp of the event. UTC timestamp millis.
       * </pre>
       *
       * <code>uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * Timestamp of the event. UTC timestamp millis.
       * </pre>
       *
       * <code>uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp of the event. UTC timestamp millis.
       * </pre>
       *
       * <code>uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * Type of event.
       * </pre>
       *
       * <code>.EventType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * Type of event.
       * </pre>
       *
       * <code>.EventType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of event.
       * </pre>
       *
       * <code>.EventType type = 3;</code>
       */
      public tracker.datatypes.Events.EventType getType() {
        tracker.datatypes.Events.EventType result = tracker.datatypes.Events.EventType.valueOf(type_);
        return result == null ? tracker.datatypes.Events.EventType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Type of event.
       * </pre>
       *
       * <code>.EventType type = 3;</code>
       */
      public Builder setType(tracker.datatypes.Events.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of event.
       * </pre>
       *
       * <code>.EventType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString deviceId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Unique device (~ user) identifier. UUID (128 bit), big endian.
       * Typically stored in a cookie in the browser.
       * </pre>
       *
       * <code>bytes device_id = 4;</code>
       */
      public com.google.protobuf.ByteString getDeviceId() {
        return deviceId_;
      }
      /**
       * <pre>
       * Unique device (~ user) identifier. UUID (128 bit), big endian.
       * Typically stored in a cookie in the browser.
       * </pre>
       *
       * <code>bytes device_id = 4;</code>
       */
      public Builder setDeviceId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique device (~ user) identifier. UUID (128 bit), big endian.
       * Typically stored in a cookie in the browser.
       * </pre>
       *
       * <code>bytes device_id = 4;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Event)
    }

    // @@protoc_insertion_point(class_scope:Event)
    private static final tracker.datatypes.Events.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tracker.datatypes.Events.Event();
    }

    public static tracker.datatypes.Events.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    public tracker.datatypes.Events.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Conversion event ID. UUID (128 bit), big endian.
     * </pre>
     *
     * <code>bytes conversion_event_id = 1;</code>
     */
    com.google.protobuf.ByteString getConversionEventId();

    /**
     * <pre>
     * Referring event ID. UUID (128 bit), big endian.
     * </pre>
     *
     * <code>bytes referrer_event_id = 2;</code>
     */
    com.google.protobuf.ByteString getReferrerEventId();

    /**
     * <pre>
     * Type of the referrer event (IMPRESSION or CLICK).
     * </pre>
     *
     * <code>.EventType referrer_type = 3;</code>
     */
    int getReferrerTypeValue();
    /**
     * <pre>
     * Type of the referrer event (IMPRESSION or CLICK).
     * </pre>
     *
     * <code>.EventType referrer_type = 3;</code>
     */
    tracker.datatypes.Events.EventType getReferrerType();
  }
  /**
   * <pre>
   * Output Data
   * </pre>
   *
   * Protobuf type {@code Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result)
      ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      conversionEventId_ = com.google.protobuf.ByteString.EMPTY;
      referrerEventId_ = com.google.protobuf.ByteString.EMPTY;
      referrerType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              conversionEventId_ = input.readBytes();
              break;
            }
            case 18: {

              referrerEventId_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              referrerType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tracker.datatypes.Events.internal_static_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tracker.datatypes.Events.internal_static_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tracker.datatypes.Events.Result.class, tracker.datatypes.Events.Result.Builder.class);
    }

    public static final int CONVERSION_EVENT_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString conversionEventId_;
    /**
     * <pre>
     * Conversion event ID. UUID (128 bit), big endian.
     * </pre>
     *
     * <code>bytes conversion_event_id = 1;</code>
     */
    public com.google.protobuf.ByteString getConversionEventId() {
      return conversionEventId_;
    }

    public static final int REFERRER_EVENT_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString referrerEventId_;
    /**
     * <pre>
     * Referring event ID. UUID (128 bit), big endian.
     * </pre>
     *
     * <code>bytes referrer_event_id = 2;</code>
     */
    public com.google.protobuf.ByteString getReferrerEventId() {
      return referrerEventId_;
    }

    public static final int REFERRER_TYPE_FIELD_NUMBER = 3;
    private int referrerType_;
    /**
     * <pre>
     * Type of the referrer event (IMPRESSION or CLICK).
     * </pre>
     *
     * <code>.EventType referrer_type = 3;</code>
     */
    public int getReferrerTypeValue() {
      return referrerType_;
    }
    /**
     * <pre>
     * Type of the referrer event (IMPRESSION or CLICK).
     * </pre>
     *
     * <code>.EventType referrer_type = 3;</code>
     */
    public tracker.datatypes.Events.EventType getReferrerType() {
      tracker.datatypes.Events.EventType result = tracker.datatypes.Events.EventType.valueOf(referrerType_);
      return result == null ? tracker.datatypes.Events.EventType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!conversionEventId_.isEmpty()) {
        output.writeBytes(1, conversionEventId_);
      }
      if (!referrerEventId_.isEmpty()) {
        output.writeBytes(2, referrerEventId_);
      }
      if (referrerType_ != tracker.datatypes.Events.EventType.UNKNOWN.getNumber()) {
        output.writeEnum(3, referrerType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!conversionEventId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, conversionEventId_);
      }
      if (!referrerEventId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, referrerEventId_);
      }
      if (referrerType_ != tracker.datatypes.Events.EventType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, referrerType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tracker.datatypes.Events.Result)) {
        return super.equals(obj);
      }
      tracker.datatypes.Events.Result other = (tracker.datatypes.Events.Result) obj;

      boolean result = true;
      result = result && getConversionEventId()
          .equals(other.getConversionEventId());
      result = result && getReferrerEventId()
          .equals(other.getReferrerEventId());
      result = result && referrerType_ == other.referrerType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONVERSION_EVENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getConversionEventId().hashCode();
      hash = (37 * hash) + REFERRER_EVENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getReferrerEventId().hashCode();
      hash = (37 * hash) + REFERRER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + referrerType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tracker.datatypes.Events.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracker.datatypes.Events.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracker.datatypes.Events.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracker.datatypes.Events.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracker.datatypes.Events.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tracker.datatypes.Events.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tracker.datatypes.Events.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tracker.datatypes.Events.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tracker.datatypes.Events.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tracker.datatypes.Events.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tracker.datatypes.Events.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tracker.datatypes.Events.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tracker.datatypes.Events.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Output Data
     * </pre>
     *
     * Protobuf type {@code Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result)
        tracker.datatypes.Events.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tracker.datatypes.Events.internal_static_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tracker.datatypes.Events.internal_static_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tracker.datatypes.Events.Result.class, tracker.datatypes.Events.Result.Builder.class);
      }

      // Construct using tracker.Events.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        conversionEventId_ = com.google.protobuf.ByteString.EMPTY;

        referrerEventId_ = com.google.protobuf.ByteString.EMPTY;

        referrerType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tracker.datatypes.Events.internal_static_Result_descriptor;
      }

      public tracker.datatypes.Events.Result getDefaultInstanceForType() {
        return tracker.datatypes.Events.Result.getDefaultInstance();
      }

      public tracker.datatypes.Events.Result build() {
        tracker.datatypes.Events.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tracker.datatypes.Events.Result buildPartial() {
        tracker.datatypes.Events.Result result = new tracker.datatypes.Events.Result(this);
        result.conversionEventId_ = conversionEventId_;
        result.referrerEventId_ = referrerEventId_;
        result.referrerType_ = referrerType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tracker.datatypes.Events.Result) {
          return mergeFrom((tracker.datatypes.Events.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tracker.datatypes.Events.Result other) {
        if (other == tracker.datatypes.Events.Result.getDefaultInstance()) return this;
        if (other.getConversionEventId() != com.google.protobuf.ByteString.EMPTY) {
          setConversionEventId(other.getConversionEventId());
        }
        if (other.getReferrerEventId() != com.google.protobuf.ByteString.EMPTY) {
          setReferrerEventId(other.getReferrerEventId());
        }
        if (other.referrerType_ != 0) {
          setReferrerTypeValue(other.getReferrerTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tracker.datatypes.Events.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tracker.datatypes.Events.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString conversionEventId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Conversion event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes conversion_event_id = 1;</code>
       */
      public com.google.protobuf.ByteString getConversionEventId() {
        return conversionEventId_;
      }
      /**
       * <pre>
       * Conversion event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes conversion_event_id = 1;</code>
       */
      public Builder setConversionEventId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        conversionEventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Conversion event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes conversion_event_id = 1;</code>
       */
      public Builder clearConversionEventId() {
        
        conversionEventId_ = getDefaultInstance().getConversionEventId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString referrerEventId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Referring event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes referrer_event_id = 2;</code>
       */
      public com.google.protobuf.ByteString getReferrerEventId() {
        return referrerEventId_;
      }
      /**
       * <pre>
       * Referring event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes referrer_event_id = 2;</code>
       */
      public Builder setReferrerEventId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        referrerEventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Referring event ID. UUID (128 bit), big endian.
       * </pre>
       *
       * <code>bytes referrer_event_id = 2;</code>
       */
      public Builder clearReferrerEventId() {
        
        referrerEventId_ = getDefaultInstance().getReferrerEventId();
        onChanged();
        return this;
      }

      private int referrerType_ = 0;
      /**
       * <pre>
       * Type of the referrer event (IMPRESSION or CLICK).
       * </pre>
       *
       * <code>.EventType referrer_type = 3;</code>
       */
      public int getReferrerTypeValue() {
        return referrerType_;
      }
      /**
       * <pre>
       * Type of the referrer event (IMPRESSION or CLICK).
       * </pre>
       *
       * <code>.EventType referrer_type = 3;</code>
       */
      public Builder setReferrerTypeValue(int value) {
        referrerType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of the referrer event (IMPRESSION or CLICK).
       * </pre>
       *
       * <code>.EventType referrer_type = 3;</code>
       */
      public tracker.datatypes.Events.EventType getReferrerType() {
        tracker.datatypes.Events.EventType result = tracker.datatypes.Events.EventType.valueOf(referrerType_);
        return result == null ? tracker.datatypes.Events.EventType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Type of the referrer event (IMPRESSION or CLICK).
       * </pre>
       *
       * <code>.EventType referrer_type = 3;</code>
       */
      public Builder setReferrerType(tracker.datatypes.Events.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        referrerType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of the referrer event (IMPRESSION or CLICK).
       * </pre>
       *
       * <code>.EventType referrer_type = 3;</code>
       */
      public Builder clearReferrerType() {
        
        referrerType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Result)
    }

    // @@protoc_insertion_point(class_scope:Result)
    private static final tracker.datatypes.Events.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tracker.datatypes.Events.Result();
    }

    public static tracker.datatypes.Events.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    public tracker.datatypes.Events.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Event_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/resources/event.proto\"S\n\005Even" +
      "t\022\n\n\002id\030\001 \001(\014\022\021\n\ttimestamp\030\002 \001(\004\022\030\n\004type" +
      "\030\003 \001(\0162\n.EventType\022\021\n\tdevice_id\030\004 \001(\014\"c\n" +
      "\006Result\022\033\n\023conversion_event_id\030\001 \001(\014\022\031\n\021" +
      "referrer_event_id\030\002 \001(\014\022!\n\rreferrer_type" +
      "\030\003 \001(\0162\n.EventType*C\n\tEventType\022\013\n\007UNKNO" +
      "WN\020\000\022\016\n\nIMPRESSION\020\001\022\t\n\005CLICK\020\002\022\016\n\nCONVE" +
      "RSION\020\003B\021\n\007trackerB\006Eventsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Event_descriptor,
        new java.lang.String[] { "Id", "Timestamp", "Type", "DeviceId", });
    internal_static_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result_descriptor,
        new java.lang.String[] { "ConversionEventId", "ReferrerEventId", "ReferrerType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
